import { Era } from './types';

export const ERAS: Era[] = [
  {
    id: 'cyberpunk',
    name: 'Cyberpunk 2077',
    description: 'Neon lights, cybernetic enhancements, and high-tech street wear.',
    prompt: 'Transform this person into a futuristic cyberpunk character. Add subtle glowing cybernetic lines on the face, neon city lighting background, high-tech tactical clothing. Retain facial identity but style as a high-quality sci-fi movie character.',
    icon: '⚡',
    gradient: 'from-pink-500 via-purple-500 to-indigo-500',
  },
  {
    id: 'kpop',
    name: 'K-Pop Idol',
    description: 'Stage lights, glass skin, and chart-topping style.',
    prompt: 'Transform this person into a K-Pop idol superstar. Flawless skin, trendy hair style, high-fashion stage outfit. Background is a vibrant music video set with neon lights and soft bokeh. Vibrant, glossy, high-production value aesthetic.',
    icon: '🎤',
    gradient: 'from-pink-500 via-fuchsia-500 to-purple-500',
  },
  {
    id: '1920s',
    name: 'Roaring Twenties',
    description: 'The Great Gatsby style, art deco, and vintage glamour.',
    prompt: 'Transform this person into a 1920s jazz age character. Sepia or black and white photography style. For men: tuxedo, slicked hair, vintage atmosphere. For women: flapper dress, bobbed hair, pearls. High detail vintage photograph style.',
    icon: '🎷',
    gradient: 'from-yellow-600 via-yellow-500 to-amber-400',
  },
  {
    id: 'medieval',
    name: 'Medieval Knight',
    description: 'Epic armor, castles, and fantasy heroism.',
    prompt: 'Transform this person into a medieval fantasy knight or royalty. Metal plate armor or regal velvet robes. Castle courtyard background. Dramatic lighting, oil painting style. Retain facial identity.',
    icon: '⚔️',
    gradient: 'from-slate-700 via-slate-600 to-slate-500',
  },
  {
    id: 'wild_west',
    name: 'Wild West',
    description: 'Cowboys, saloons, and the dusty frontier.',
    prompt: 'Transform this person into a Wild West cowboy or cowgirl. Leather hat, dusty coat, desert canyon background. Warm golden hour lighting. Cinematic western movie style.',
    icon: '🤠',
    gradient: 'from-orange-700 via-orange-600 to-amber-700',
  },
  {
    id: 'vikings',
    name: 'Viking Era',
    description: 'Furs, braids, and snowy fjords.',
    prompt: 'Transform this person into a fierce Viking warrior. Fur cloak, leather armor, dramatic snowy fjord background. Cold blue toning, cinematic realism.',
    icon: '🛡️',
    gradient: 'from-sky-800 via-blue-700 to-indigo-800',
  },
  {
    id: 'egypt',
    name: 'Ancient Egypt',
    description: 'Pharaohs, gold, and desert sands.',
    prompt: 'Transform this person into an Ancient Egyptian noble or Pharaoh. Gold jewelry, linen garments, temple background with hieroglyphs. Warm sunlight, historical reconstruction style.',
    icon: '🏺',
    gradient: 'from-yellow-500 via-amber-400 to-yellow-600',
  },
  {
    id: 'victorian',
    name: 'Victorian Era',
    description: 'Top hats, corsets, and industrial steam.',
    prompt: 'Transform this person into a Victorian era aristocrat. Formal coat/dress, misty London street background. Steampunk subtle hints optional. Moody, desaturated color palette.',
    icon: '🎩',
    gradient: 'from-gray-800 via-gray-700 to-gray-900',
  },
  {
    id: 'astronaut',
    name: 'Space Explorer',
    description: 'NASA suits and the surface of Mars.',
    prompt: 'Transform this person into a modern astronaut. White space suit, helmet off (holding it or visor open), Mars surface background or ISS interior. Crisp, high-definition NASA photography style.',
    icon: '🚀',
    gradient: 'from-blue-600 via-indigo-600 to-purple-600',
  },
];